"use client";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./_components/header/Header";
import Footer from "./_components/footer/Footer";
import { usePathname } from "next/navigation";
import AuthProvider from "./authContext/authContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();
  const hiddenLayout = ["/login", "/register"];
  const shouldHideLayout = hiddenLayout.includes(pathname);
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* {!shouldHideLayout && <Header />} */}
        <AuthProvider>
          <Header />
          {children}
          <Footer />
          {/* {!shouldHideLayout &&  <Footer />} */}
        </AuthProvider>
      </body>
    </html>
  );
}
